services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./ssl:/app/ssl
    environment:
      - DATABASE_URL=sqlite:///./data/test.db
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - CORS_ORIGINS=https://*.ngrok-free.app
      - ENVIRONMENT=development
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN} # 從環境變數讀取您的 ngrok token
    command: http https://backend:8000 --domain gently-flowing-halibut.ngrok-free.app # 將 your-custom-domain.ngrok-free.app 換成您自己的
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ai-cyber-dataset-review-ollama
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: 